ProtoCI/Models/AgentViewModel.cs
using System.Web;
using ProtoCI.Core.Entities;

namespace ProtoCI.Models
{
    public class AgentViewModel
    {
        public Agent AgentData { get; set; }

        public HttpPostedFileBase PrivateKeyFile { get; set; }
    }
}

ProtoCI/Controllers/AgentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Ninject;
using ProtoCI.Core;
using ProtoCI.Core.Entities;
using ProtoCI.Core.Protocols;
using ProtoCI.DAL;
using ProtoCI.Models;

namespace ProtoCI.Controllers
{
    public class AgentsController : Controller
    {
        private readonly IProtocol _sshProtocol;
        private readonly IProtocol _winrmProtocol;

        private AgentContext db = new AgentContext();

        public AgentsController(
            [Named("SSH")] IProtocol sshProtocol,
            [Named("WinRM")] IProtocol winrmProtocol)
        {
            _sshProtocol = sshProtocol;
            _winrmProtocol = winrmProtocol;
        }

        // GET: Agents
        public async Task<ActionResult> Index()
        {
            return View(await db.Agents.ToListAsync());
        }

        // GET: Agents/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agent agent = await db.Agents.FindAsync(id);
            if (agent == null)
            {
                return HttpNotFound();
            }
            return View(agent);
        }

        // GET: Agents/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Agents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(AgentViewModel agentViewModel)
        {
            if (ModelState.IsValid)
            {
                if (agentViewModel.PrivateKeyFile != null)
                {
                    var target = new MemoryStream();
                    agentViewModel.PrivateKeyFile.InputStream.CopyTo(target);
                    agentViewModel.AgentData.PrivateKeyBytes = target.ToArray();
                }

                db.Agents.Add(agentViewModel.AgentData);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(agentViewModel);
        }

        // GET: Agents/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agent agent = await db.Agents.FindAsync(id);
            if (agent == null)
            {
                return HttpNotFound();
            }
            return View(new AgentViewModel { AgentData = agent });
        }

        // POST: Agents/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(AgentViewModel agentViewModel)
        {
            if (ModelState.IsValid)
            {
                if (agentViewModel.PrivateKeyFile != null)
                {
                    var target = new MemoryStream();
                    agentViewModel.PrivateKeyFile.InputStream.CopyTo(target);
                    agentViewModel.AgentData.PrivateKeyBytes = target.ToArray();
                }

                db.Entry(agentViewModel.AgentData).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(agentViewModel);
        }

        // GET: Agents/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agent agent = await db.Agents.FindAsync(id);
            if (agent == null)
            {
                return HttpNotFound();
            }
            return View(agent);
        }

        // POST: Agents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Agent agent = await db.Agents.FindAsync(id);
            db.Agents.Remove(agent);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public async Task<ActionResult> Test(int id)
        {
            var agent = await db.Agents.FindAsync(id);

            var model = new AgentTestViewModel();
            try
            {
                var protocol = agent.PlatformType == AgentPlatformType.Windows
                    ? _winrmProtocol
                    : _sshProtocol;

                var conn = protocol.OpenConnection(agent);
                string output;
                try
                {
                    var commandText = agent.PlatformType == AgentPlatformType.Windows
                        ? "$env:COMPUTERNAME"
                        : "uname -a";

                    var cmd = protocol.StartCommand(conn, commandText, ".");
                    using (var reader = new StreamReader(cmd.StandardOutput))
                    {
                        output = reader.ReadToEnd();
                    }
                }
                finally
                {
                    protocol.CloseConnection(agent);
                }

                model.SystemIdentifier = output;
            }
            catch (Exception ex)
            {
                model.Exception = ex;
            }

            return View(model);
        }
    }
}

ProtoCI/Views/Agents/Create.cshtml
@model ProtoCI.Models.AgentViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Edit", "Agents", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Agent</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.AgentData.PlatformType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.AgentData.PlatformType, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AgentData.PlatformType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AgentData.Host, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AgentData.Host, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AgentData.Host, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AgentData.Port, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AgentData.Port, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AgentData.Port, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AgentData.StoragePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AgentData.StoragePath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AgentData.StoragePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AgentData.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AgentData.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AgentData.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AgentData.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AgentData.Password, new { htmlAttributes = new { @class = "form-control", type = "password" } })
                @Html.ValidationMessageFor(model => model.AgentData.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrivateKeyFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.PrivateKeyFile, new { @class = "form-control", type = "file" })
                @Html.ValidationMessageFor(model => model.PrivateKeyFile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProtoCI/Views/Agents/Delete.cshtml
@model ProtoCI.Core.Entities.Agent

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Agent</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PlatformType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlatformType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Host)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Host)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Port)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Port)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrivateKeyBytes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrivateKeyBytes)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ProtoCI/Views/Agents/Details.cshtml
@model ProtoCI.Core.Entities.Agent

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Agent</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PlatformType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlatformType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Host)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Host)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Port)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Port)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrivateKeyBytes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrivateKeyBytes)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ProtoCI/Views/Agents/Edit.cshtml
@model ProtoCI.Models.AgentViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Agents", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Agent</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.AgentData.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.AgentData.PlatformType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.AgentData.PlatformType, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AgentData.PlatformType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AgentData.Host, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AgentData.Host, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AgentData.Host, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AgentData.Port, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.AgentData.Port, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.AgentData.Port, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AgentData.StoragePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AgentData.StoragePath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AgentData.StoragePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AgentData.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AgentData.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AgentData.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AgentData.Password, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.AgentData.Password, new {htmlAttributes = new {@class = "form-control", type = "password"}})
                @Html.ValidationMessageFor(model => model.AgentData.Password, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrivateKeyFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.PrivateKeyFile, new { @class = "form-control", type="file" })
                @Html.ValidationMessageFor(model => model.PrivateKeyFile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProtoCI/Views/Agents/Index.cshtml
@model IEnumerable<ProtoCI.Core.Entities.Agent>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PlatformType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Host)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Port)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Username)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.PlatformType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Host)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Port)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Username)
        </td>
        <td>
            @Html.ActionLink("Test", "Test", new { id = item.ID }) |
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

ProtoCI/Views/Agents/Test.cshtml
@model ProtoCI.Models.AgentTestViewModel

@{
    ViewBag.Title = "Test Connection";
}

<h2>Test Connection</h2>
@if (Model.Exception == null)
{
    <h3>Connection Successful</h3>
    <p>
        @Model.SystemIdentifier
    </p>
}
else
{
    <h3>Connection Failed</h3>
    <div class="alert alert-danger">
        @Model.Exception.Message<br/>
        @Model.Exception.StackTrace
    </div>
}